#pragma once

#define SESSION_SEND_BUFFER_DEFAULT_SIZE	20000
#define SESSION_RECV_BUFFER_DEFAULT_SIZE	20000

//#define SEND_RECV_RING_BUFF_COPY_MODE
#define SEND_RECV_RING_BUFF_SERIALIZATION_MODE
#if defined(SEND_RECV_RING_BUFF_SERIALIZATION_MODE)
#define WSABUF_ARRAY_DEFAULT_SIZE			1000
#endif

#define ALLOC_BY_TLS_MEM_POOL
#if defined(ALLOC_BY_TLS_MEM_POOL)	
#define TLS_MEM_POOL_DEFAULT_ALLOC_SIZE		0		
#define TLS_MEM_POOL_DEFAULT_SURPLUS_SIZE	100
#endif