#pragma once

#define LOCKFREE_MESSAGE_QUEUE
#if defined(LOCKFREE_MESSAGE_QUEUE)
#define	LOCKFREE_GROUP_MESSAGE_QUEUE
//#define LOCKFREE_SESSION_MESSAGE_QUEUE
#else
#define SETEVENT_RECEIVE_EVENT
//#define POLLING_RECEIVE_EVENT
//#define POLLING_SESSION_MESSAGE_QUEUE
#endif